package catalog

// sports is the full catalog. Adding a sport here is all that is required to
// make it bettable: navigation, market generation, settlement wiring and the
// admin event builder all read from this table.
//
// Deliberately absent: political, entertainment and other non-sport novelty
// markets. They are separately regulated in most jurisdictions and several
// licences that permit sports betting forbid them outright, so they are not
// part of a "sportsbook" product by default.
var sports = []Sport{
	// -----------------------------------------------------------------
	// Football codes
	// -----------------------------------------------------------------
	{"football", "Football", CatFootballCodes, ScoringGoals, []Format{FormatMatch, FormatTournament}, true, periodsHalves, withSeason(marketsTeamDraw),
		[]string{"Premier League", "La Liga", "Serie A", "Bundesliga", "Ligue 1", "UEFA Champions League", "FIFA World Cup", "Copa Libertadores", "MLS"}, 0},
	{"american-football", "American Football", CatFootballCodes, ScoringPoints, []Format{FormatMatch, FormatTournament}, true, periodsQuarters, withSeason(marketsTeamDraw),
		[]string{"NFL", "NCAA Division I", "XFL", "CFL"}, 0},
	{"australian-rules", "Australian Rules Football", CatFootballCodes, ScoringPoints, []Format{FormatMatch, FormatTournament}, true, periodsQuarters, withSeason(marketsTeamDraw),
		[]string{"AFL", "AFL Women's", "VFL"}, 0},
	{"gaelic-football", "Gaelic Football", CatFootballCodes, ScoringPoints, []Format{FormatMatch, FormatTournament}, true, periodsHalves, withSeason(marketsTeamDraw),
		[]string{"All-Ireland Senior Championship", "National Football League"}, 0},
	{"rugby-union", "Rugby Union", CatFootballCodes, ScoringPoints, []Format{FormatMatch, FormatTournament}, true, periodsHalves, withSeason(marketsTeamDraw),
		[]string{"Six Nations", "Rugby World Cup", "United Rugby Championship", "Premiership Rugby", "Top 14", "The Rugby Championship"}, 0},
	{"rugby-league", "Rugby League", CatFootballCodes, ScoringPoints, []Format{FormatMatch, FormatTournament}, true, periodsHalves, withSeason(marketsTeamDraw),
		[]string{"NRL", "Super League", "State of Origin", "Rugby League World Cup"}, 0},
	{"rugby-sevens", "Rugby Sevens", CatFootballCodes, ScoringPoints, []Format{FormatMatch, FormatTournament}, true, periodsHalves, withSeason(marketsTeamDraw),
		[]string{"World Rugby Sevens Series", "Olympic Sevens"}, 0},
	{"canadian-football", "Canadian Football", CatFootballCodes, ScoringPoints, []Format{FormatMatch, FormatTournament}, true, periodsQuarters, withSeason(marketsTeamDraw),
		[]string{"CFL", "Grey Cup"}, 0},
	{"futsal", "Futsal", CatFootballCodes, ScoringGoals, []Format{FormatMatch, FormatTournament}, true, periodsHalves, withSeason(marketsTeamDraw),
		[]string{"UEFA Futsal Champions League", "FIFA Futsal World Cup"}, 0},
	{"beach-soccer", "Beach Soccer", CatFootballCodes, ScoringGoals, []Format{FormatMatch, FormatTournament}, false, periodsThirds, withSeason(marketsTeamNoDraw),
		[]string{"FIFA Beach Soccer World Cup", "Euro Beach Soccer League"}, 0},

	// -----------------------------------------------------------------
	// Team sports
	// -----------------------------------------------------------------
	{"basketball", "Basketball", CatTeamSports, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, periodsQuarters, withSeason(marketsTeamNoDraw),
		[]string{"NBA", "EuroLeague", "NCAA March Madness", "WNBA", "FIBA World Cup", "Liga ACB"}, 0},
	{"basketball-3x3", "3x3 Basketball", CatTeamSports, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, periodsNone, marketsTeamNoDraw,
		[]string{"FIBA 3x3 World Tour", "Olympic 3x3"}, 0},
	{"baseball", "Baseball", CatTeamSports, ScoringRuns, []Format{FormatMatch, FormatTournament}, false, []string{"1st Innings", "First 5 Innings"}, withSeason(marketsTeamNoDraw),
		[]string{"MLB", "Nippon Professional Baseball", "KBO League", "World Baseball Classic"}, 0},
	{"softball", "Softball", CatTeamSports, ScoringRuns, []Format{FormatMatch, FormatTournament}, false, periodsNone, withSeason(marketsTeamNoDraw),
		[]string{"WBSC World Cup", "NCAA Softball"}, 0},
	{"ice-hockey", "Ice Hockey", CatTeamSports, ScoringGoals, []Format{FormatMatch, FormatTournament}, true, periodsThirds, withSeason(marketsTeamDraw),
		[]string{"NHL", "KHL", "IIHF World Championship", "SHL", "Liiga"}, 0},
	{"field-hockey", "Field Hockey", CatTeamSports, ScoringGoals, []Format{FormatMatch, FormatTournament}, true, periodsQuarters, withSeason(marketsTeamDraw),
		[]string{"FIH Pro League", "Hockey World Cup", "Olympic Hockey"}, 0},
	{"handball", "Handball", CatTeamSports, ScoringGoals, []Format{FormatMatch, FormatTournament}, true, periodsHalves, withSeason(marketsTeamDraw),
		[]string{"EHF Champions League", "IHF World Championship", "Handball-Bundesliga"}, 0},
	{"volleyball", "Volleyball", CatTeamSports, ScoringSets, []Format{FormatMatch, FormatTournament}, false, periodsSets, withSeason(marketsRacket),
		[]string{"FIVB Volleyball Nations League", "CEV Champions League", "Olympic Volleyball"}, 0},
	{"beach-volleyball", "Beach Volleyball", CatTeamSports, ScoringSets, []Format{FormatMatch, FormatTournament}, false, []string{"Set 1", "Set 2", "Set 3"}, marketsRacket,
		[]string{"Beach Pro Tour", "Olympic Beach Volleyball"}, 0},
	{"cricket", "Cricket", CatTeamSports, ScoringRuns, []Format{FormatMatch, FormatTournament}, true, periodsInnings, withSeason(marketsCricket),
		[]string{"ICC Cricket World Cup", "The Ashes", "Indian Premier League", "Big Bash League", "ICC T20 World Cup", "County Championship"}, 0},
	{"water-polo", "Water Polo", CatTeamSports, ScoringGoals, []Format{FormatMatch, FormatTournament}, true, periodsQuarters, withSeason(marketsTeamDraw),
		[]string{"World Aquatics Championships", "LEN Champions League", "Olympic Water Polo"}, 0},
	{"lacrosse", "Lacrosse", CatTeamSports, ScoringGoals, []Format{FormatMatch, FormatTournament}, false, periodsQuarters, withSeason(marketsTeamNoDraw),
		[]string{"National Lacrosse League", "Premier Lacrosse League", "World Lacrosse Championship"}, 0},
	{"netball", "Netball", CatTeamSports, ScoringGoals, []Format{FormatMatch, FormatTournament}, true, periodsQuarters, withSeason(marketsTeamDraw),
		[]string{"Netball World Cup", "Suncorp Super Netball", "Netball Superleague"}, 0},
	{"bandy", "Bandy", CatTeamSports, ScoringGoals, []Format{FormatMatch, FormatTournament}, true, periodsHalves, withSeason(marketsTeamDraw),
		[]string{"Bandy World Championship", "Elitserien"}, 0},
	{"floorball", "Floorball", CatTeamSports, ScoringGoals, []Format{FormatMatch, FormatTournament}, true, periodsThirds, withSeason(marketsTeamDraw),
		[]string{"Floorball World Championships", "Superliga"}, 0},
	{"korfball", "Korfball", CatTeamSports, ScoringGoals, []Format{FormatMatch, FormatTournament}, true, periodsHalves, withSeason(marketsTeamDraw),
		[]string{"IKF Korfball World Cup", "Korfball League"}, 0},
	{"kabaddi", "Kabaddi", CatTeamSports, ScoringPoints, []Format{FormatMatch, FormatTournament}, true, periodsHalves, withSeason(marketsTeamDraw),
		[]string{"Pro Kabaddi League", "Kabaddi World Cup"}, 0},
	{"sepak-takraw", "Sepak Takraw", CatTeamSports, ScoringSets, []Format{FormatMatch, FormatTournament}, false, []string{"Set 1", "Set 2", "Set 3"}, marketsRacket,
		[]string{"ISTAF SuperSeries", "King's Cup"}, 0},
	{"ultimate", "Ultimate Frisbee", CatTeamSports, ScoringGoals, []Format{FormatMatch, FormatTournament}, false, periodsQuarters, withSeason(marketsTeamNoDraw),
		[]string{"AUDL", "WFDF World Championships"}, 0},
	{"roller-hockey", "Roller Hockey", CatTeamSports, ScoringGoals, []Format{FormatMatch, FormatTournament}, true, periodsHalves, withSeason(marketsTeamDraw),
		[]string{"World Skate Games", "OK Liga"}, 0},
	{"hurling", "Hurling", CatTeamSports, ScoringPoints, []Format{FormatMatch, FormatTournament}, true, periodsHalves, withSeason(marketsTeamDraw),
		[]string{"All-Ireland Senior Hurling Championship", "National Hurling League"}, 0},
	{"camogie", "Camogie", CatTeamSports, ScoringPoints, []Format{FormatMatch, FormatTournament}, true, periodsHalves, withSeason(marketsTeamDraw),
		[]string{"All-Ireland Senior Camogie Championship"}, 0},
	{"shinty", "Shinty", CatTeamSports, ScoringGoals, []Format{FormatMatch, FormatTournament}, true, periodsHalves, withSeason(marketsTeamDraw),
		[]string{"Camanachd Cup", "Mowi Premiership"}, 0},
	{"jai-alai", "Jai Alai", CatTeamSports, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, periodsNone, marketsTeamNoDraw,
		[]string{"Jai Alai World Tour"}, 0},

	// -----------------------------------------------------------------
	// Racket sports
	// -----------------------------------------------------------------
	{"tennis", "Tennis", CatRacket, ScoringSets, []Format{FormatMatch, FormatTournament}, false, periodsSets, marketsRacket,
		[]string{"Australian Open", "Roland Garros", "Wimbledon", "US Open", "ATP Tour", "WTA Tour", "Davis Cup"}, 0},
	{"table-tennis", "Table Tennis", CatRacket, ScoringSets, []Format{FormatMatch, FormatTournament}, false, periodsSets, marketsRacket,
		[]string{"ITTF World Championships", "WTT Champions", "Olympic Table Tennis"}, 0},
	{"badminton", "Badminton", CatRacket, ScoringSets, []Format{FormatMatch, FormatTournament}, false, []string{"Game 1", "Game 2", "Game 3"}, marketsRacket,
		[]string{"BWF World Championships", "All England Open", "Thomas Cup"}, 0},
	{"squash", "Squash", CatRacket, ScoringSets, []Format{FormatMatch, FormatTournament}, false, periodsSets, marketsRacket,
		[]string{"PSA World Championships", "British Open"}, 0},
	{"padel", "Padel", CatRacket, ScoringSets, []Format{FormatMatch, FormatTournament}, false, []string{"Set 1", "Set 2", "Set 3"}, marketsRacket,
		[]string{"Premier Padel", "World Padel Tour"}, 0},
	{"racquetball", "Racquetball", CatRacket, ScoringSets, []Format{FormatMatch, FormatTournament}, false, []string{"Game 1", "Game 2", "Game 3"}, marketsRacket,
		[]string{"IRF World Championships"}, 0},
	{"pickleball", "Pickleball", CatRacket, ScoringSets, []Format{FormatMatch, FormatTournament}, false, []string{"Game 1", "Game 2", "Game 3"}, marketsRacket,
		[]string{"PPA Tour", "Major League Pickleball"}, 0},

	// -----------------------------------------------------------------
	// Combat sports
	// -----------------------------------------------------------------
	{"boxing", "Boxing", CatCombat, ScoringRounds, []Format{FormatMatch, FormatTournament}, true, periodsNone, marketsCombat,
		[]string{"WBC", "WBA", "IBF", "WBO", "Olympic Boxing"}, 0},
	{"mma", "Mixed Martial Arts", CatCombat, ScoringRounds, []Format{FormatMatch, FormatTournament}, true, periodsNone, marketsCombat,
		[]string{"UFC", "Bellator", "ONE Championship", "PFL"}, 0},
	{"kickboxing", "Kickboxing", CatCombat, ScoringRounds, []Format{FormatMatch, FormatTournament}, true, periodsNone, marketsCombat,
		[]string{"GLORY Kickboxing", "K-1"}, 0},
	{"muay-thai", "Muay Thai", CatCombat, ScoringRounds, []Format{FormatMatch, FormatTournament}, true, periodsNone, marketsCombat,
		[]string{"ONE Muay Thai", "Rajadamnern Stadium"}, 0},
	{"bare-knuckle", "Bare-Knuckle Boxing", CatCombat, ScoringRounds, []Format{FormatMatch, FormatTournament}, true, periodsNone, marketsCombat,
		[]string{"BKFC"}, 0},
	{"wrestling", "Wrestling", CatCombat, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, periodsHalves, marketsCombat,
		[]string{"UWW World Championships", "Olympic Wrestling"}, 0},
	{"judo", "Judo", CatCombat, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, periodsNone, marketsCombat,
		[]string{"IJF World Championships", "Olympic Judo"}, 0},
	{"karate", "Karate", CatCombat, ScoringPoints, []Format{FormatMatch, FormatTournament}, true, periodsNone, marketsCombat,
		[]string{"Karate1 Premier League", "WKF World Championships"}, 0},
	{"taekwondo", "Taekwondo", CatCombat, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, periodsThirds, marketsCombat,
		[]string{"World Taekwondo Championships", "Olympic Taekwondo"}, 0},
	{"sumo", "Sumo", CatCombat, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, periodsNone, marketsCombat,
		[]string{"Grand Sumo Tournament"}, 0},
	{"sambo", "Sambo", CatCombat, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, periodsNone, marketsCombat,
		[]string{"FIAS World Sambo Championships"}, 0},
	{"jiu-jitsu", "Brazilian Jiu-Jitsu", CatCombat, ScoringPoints, []Format{FormatMatch, FormatTournament}, true, periodsNone, marketsCombat,
		[]string{"IBJJF World Championship", "ADCC"}, 0},
	{"fencing", "Fencing", CatCombat, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, periodsThirds, marketsCombat,
		[]string{"FIE World Championships", "Olympic Fencing"}, 0},

	// -----------------------------------------------------------------
	// Motorsport
	// -----------------------------------------------------------------
	{"formula-1", "Formula 1", CatMotorsport, ScoringPosition, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsMotorsport,
		[]string{"FIA Formula One World Championship"}, 3},
	{"formula-2", "Formula 2", CatMotorsport, ScoringPosition, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsMotorsport,
		[]string{"FIA Formula 2 Championship"}, 3},
	{"formula-e", "Formula E", CatMotorsport, ScoringPosition, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsMotorsport,
		[]string{"ABB FIA Formula E World Championship"}, 3},
	{"motogp", "MotoGP", CatMotorsport, ScoringPosition, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsMotorsport,
		[]string{"MotoGP World Championship", "Moto2", "Moto3"}, 3},
	{"nascar", "NASCAR", CatMotorsport, ScoringPosition, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsMotorsport,
		[]string{"NASCAR Cup Series", "Xfinity Series", "Daytona 500"}, 5},
	{"indycar", "IndyCar", CatMotorsport, ScoringPosition, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsMotorsport,
		[]string{"IndyCar Series", "Indianapolis 500"}, 3},
	{"rally", "World Rally Championship", CatMotorsport, ScoringPosition, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsStageRace,
		[]string{"WRC", "Dakar Rally"}, 3},
	{"endurance", "Endurance Racing", CatMotorsport, ScoringPosition, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsMotorsport,
		[]string{"FIA World Endurance Championship", "24 Hours of Le Mans", "IMSA"}, 3},
	{"superbike", "Superbike Racing", CatMotorsport, ScoringPosition, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsMotorsport,
		[]string{"WorldSBK", "Isle of Man TT"}, 3},
	{"motocross", "Motocross", CatMotorsport, ScoringPosition, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsMotorsport,
		[]string{"AMA Supercross", "MXGP"}, 3},
	{"touring-cars", "Touring Cars", CatMotorsport, ScoringPosition, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsMotorsport,
		[]string{"BTCC", "DTM", "WTCR", "Supercars Championship"}, 3},
	{"drag-racing", "Drag Racing", CatMotorsport, ScoringPosition, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsMotorsport,
		[]string{"NHRA Camping World Drag Racing Series"}, 3},
	{"speedway", "Speedway", CatMotorsport, ScoringPosition, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsMotorsport,
		[]string{"Speedway Grand Prix", "Speedway World Cup"}, 3},
	{"karting", "Karting", CatMotorsport, ScoringPosition, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsMotorsport,
		[]string{"FIA Karting World Championship"}, 3},

	// -----------------------------------------------------------------
	// Racing
	// -----------------------------------------------------------------
	{"horse-racing-flat", "Horse Racing (Flat)", CatAnimalRacing, ScoringPosition, []Format{FormatRace}, false, periodsNone, marketsField,
		[]string{"Epsom Derby", "Kentucky Derby", "Melbourne Cup", "Prix de l'Arc de Triomphe", "Breeders' Cup"}, 4},
	{"horse-racing-jumps", "Horse Racing (Jumps)", CatAnimalRacing, ScoringPosition, []Format{FormatRace}, false, periodsNone, marketsField,
		[]string{"Cheltenham Festival", "Grand National", "Punchestown Festival"}, 5},
	{"harness-racing", "Harness Racing", CatAnimalRacing, ScoringPosition, []Format{FormatRace}, false, periodsNone, marketsField,
		[]string{"Prix d'Amérique", "Hambletonian", "Inter Dominion"}, 4},
	{"greyhound-racing", "Greyhound Racing", CatAnimalRacing, ScoringPosition, []Format{FormatRace}, false, periodsNone, marketsField,
		[]string{"English Greyhound Derby", "Irish Greyhound Derby"}, 3},
	{"camel-racing", "Camel Racing", CatAnimalRacing, ScoringPosition, []Format{FormatRace}, false, periodsNone, marketsField,
		[]string{"Al Marmoom Heritage Festival"}, 3},

	// -----------------------------------------------------------------
	// Cycling
	// -----------------------------------------------------------------
	{"road-cycling", "Road Cycling", CatCycling, ScoringPosition, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsStageRace,
		[]string{"Tour de France", "Giro d'Italia", "Vuelta a España", "Paris-Roubaix", "UCI World Championships"}, 3},
	{"track-cycling", "Track Cycling", CatCycling, ScoringPosition, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"UCI Track Cycling World Championships", "Olympic Track Cycling"}, 3},
	{"mountain-biking", "Mountain Biking", CatCycling, ScoringPosition, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"UCI Mountain Bike World Cup"}, 3},
	{"cyclocross", "Cyclo-cross", CatCycling, ScoringPosition, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"UCI Cyclo-cross World Championships", "Superprestige"}, 3},
	{"bmx", "BMX", CatCycling, ScoringPosition, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"UCI BMX World Championships", "Olympic BMX"}, 3},

	// -----------------------------------------------------------------
	// Athletics and strength
	// -----------------------------------------------------------------
	{"athletics", "Athletics", CatAthletics, ScoringTime, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"World Athletics Championships", "Diamond League", "Olympic Athletics"}, 3},
	{"marathon", "Marathon", CatAthletics, ScoringTime, []Format{FormatRace}, false, periodsNone, marketsField,
		[]string{"London Marathon", "Boston Marathon", "Berlin Marathon", "New York City Marathon"}, 3},
	{"cross-country-running", "Cross Country Running", CatAthletics, ScoringTime, []Format{FormatRace}, false, periodsNone, marketsField,
		[]string{"World Athletics Cross Country Championships"}, 3},
	{"triathlon", "Triathlon", CatAthletics, ScoringTime, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"Ironman World Championship", "World Triathlon Championship Series"}, 3},
	{"modern-pentathlon", "Modern Pentathlon", CatAthletics, ScoringPoints, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"UIPM World Championships", "Olympic Pentathlon"}, 3},
	{"weightlifting", "Weightlifting", CatAthletics, ScoringDistance, []Format{FormatTournament}, false, periodsNone, marketsField,
		[]string{"IWF World Championships", "Olympic Weightlifting"}, 3},
	{"powerlifting", "Powerlifting", CatAthletics, ScoringDistance, []Format{FormatTournament}, false, periodsNone, marketsField,
		[]string{"IPF World Championships"}, 3},
	{"strongman", "Strongman", CatAthletics, ScoringPoints, []Format{FormatTournament}, false, periodsNone, marketsField,
		[]string{"World's Strongest Man", "Arnold Strongman Classic"}, 3},
	{"crossfit", "CrossFit", CatAthletics, ScoringPoints, []Format{FormatTournament}, false, periodsNone, marketsField,
		[]string{"CrossFit Games"}, 3},
	{"gymnastics", "Artistic Gymnastics", CatAthletics, ScoringJudged, []Format{FormatTournament}, false, periodsNone, marketsField,
		[]string{"FIG World Championships", "Olympic Gymnastics"}, 3},
	{"rhythmic-gymnastics", "Rhythmic Gymnastics", CatAthletics, ScoringJudged, []Format{FormatTournament}, false, periodsNone, marketsField,
		[]string{"FIG Rhythmic World Championships"}, 3},
	{"trampoline", "Trampoline", CatAthletics, ScoringJudged, []Format{FormatTournament}, false, periodsNone, marketsField,
		[]string{"FIG Trampoline World Championships"}, 3},

	// -----------------------------------------------------------------
	// Water sports
	// -----------------------------------------------------------------
	{"swimming", "Swimming", CatAquatics, ScoringTime, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"World Aquatics Championships", "Olympic Swimming", "International Swimming League"}, 3},
	{"open-water-swimming", "Open Water Swimming", CatAquatics, ScoringTime, []Format{FormatRace}, false, periodsNone, marketsField,
		[]string{"World Aquatics Open Water Swimming World Cup"}, 3},
	{"diving", "Diving", CatAquatics, ScoringJudged, []Format{FormatTournament}, false, periodsNone, marketsField,
		[]string{"World Aquatics Diving World Cup", "Olympic Diving"}, 3},
	{"artistic-swimming", "Artistic Swimming", CatAquatics, ScoringJudged, []Format{FormatTournament}, false, periodsNone, marketsField,
		[]string{"World Aquatics Championships"}, 3},
	{"surfing", "Surfing", CatAquatics, ScoringJudged, []Format{FormatMatch, FormatTournament}, false, periodsNone, marketsIndividual,
		[]string{"World Surf League Championship Tour", "Olympic Surfing"}, 3},
	{"sailing", "Sailing", CatAquatics, ScoringPosition, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"America's Cup", "SailGP", "Vendée Globe", "Olympic Sailing"}, 3},
	{"rowing", "Rowing", CatAquatics, ScoringTime, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"World Rowing Championships", "The Boat Race", "Olympic Rowing"}, 3},
	{"canoeing", "Canoeing & Kayaking", CatAquatics, ScoringTime, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"ICF Canoe Sprint World Championships", "ICF Canoe Slalom World Cup"}, 3},
	{"dragon-boat", "Dragon Boat Racing", CatAquatics, ScoringTime, []Format{FormatRace}, false, periodsNone, marketsField,
		[]string{"IDBF World Championships"}, 3},
	{"waterskiing", "Waterskiing & Wakeboarding", CatAquatics, ScoringJudged, []Format{FormatTournament}, false, periodsNone, marketsField,
		[]string{"IWWF World Championships"}, 3},
	{"windsurfing", "Windsurfing & Kitesurfing", CatAquatics, ScoringPosition, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"PWA World Tour", "GKA Kite World Tour"}, 3},

	// -----------------------------------------------------------------
	// Winter sports
	// -----------------------------------------------------------------
	{"alpine-skiing", "Alpine Skiing", CatWinter, ScoringTime, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"FIS Alpine Ski World Cup", "FIS Alpine World Ski Championships", "Olympic Alpine Skiing"}, 3},
	{"cross-country-skiing", "Cross-Country Skiing", CatWinter, ScoringTime, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"FIS Cross-Country World Cup", "Tour de Ski"}, 3},
	{"ski-jumping", "Ski Jumping", CatWinter, ScoringJudged, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"FIS Ski Jumping World Cup", "Four Hills Tournament"}, 3},
	{"nordic-combined", "Nordic Combined", CatWinter, ScoringPoints, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"FIS Nordic Combined World Cup"}, 3},
	{"freestyle-skiing", "Freestyle Skiing", CatWinter, ScoringJudged, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"FIS Freestyle Ski World Cup", "X Games"}, 3},
	{"snowboarding", "Snowboarding", CatWinter, ScoringJudged, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"FIS Snowboard World Cup", "X Games"}, 3},
	{"biathlon", "Biathlon", CatWinter, ScoringTime, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"IBU World Cup", "IBU World Championships"}, 3},
	{"bobsleigh", "Bobsleigh", CatWinter, ScoringTime, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"IBSF World Cup", "Olympic Bobsleigh"}, 3},
	{"skeleton", "Skeleton", CatWinter, ScoringTime, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"IBSF World Cup"}, 3},
	{"luge", "Luge", CatWinter, ScoringTime, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"FIL World Cup", "Olympic Luge"}, 3},
	{"speed-skating", "Speed Skating", CatWinter, ScoringTime, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"ISU Speed Skating World Cup", "Olympic Speed Skating"}, 3},
	{"short-track", "Short Track Speed Skating", CatWinter, ScoringTime, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"ISU Short Track World Tour"}, 3},
	{"figure-skating", "Figure Skating", CatWinter, ScoringJudged, []Format{FormatTournament}, false, periodsNone, marketsField,
		[]string{"ISU World Figure Skating Championships", "Grand Prix of Figure Skating"}, 3},
	{"curling", "Curling", CatWinter, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, []string{"End 1", "End 2", "End 3", "End 4", "End 5"}, withSeason(marketsTeamNoDraw),
		[]string{"World Curling Championships", "Olympic Curling", "Grand Slam of Curling"}, 0},

	// -----------------------------------------------------------------
	// Target and precision
	// -----------------------------------------------------------------
	{"golf", "Golf", CatTarget, ScoringStrokes, []Format{FormatMatch, FormatTournament}, true, []string{"Round 1", "Round 2", "Round 3", "Round 4"}, marketsGolf,
		[]string{"The Masters", "PGA Championship", "U.S. Open", "The Open Championship", "Ryder Cup", "LIV Golf"}, 5},
	{"darts", "Darts", CatTarget, ScoringLegs, []Format{FormatMatch, FormatTournament}, false, []string{"Set 1", "Set 2", "Set 3"}, marketsDarts,
		[]string{"PDC World Darts Championship", "Premier League Darts", "World Matchplay"}, 0},
	{"archery", "Archery", CatTarget, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, periodsNone, marketsIndividual,
		[]string{"World Archery Championships", "Olympic Archery"}, 3},
	{"shooting", "Shooting", CatTarget, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, periodsNone, marketsIndividual,
		[]string{"ISSF World Championships", "Olympic Shooting"}, 3},
	{"bowling", "Ten-Pin Bowling", CatTarget, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, periodsNone, marketsIndividual,
		[]string{"PBA Tour", "World Bowling Championships"}, 3},
	{"lawn-bowls", "Lawn Bowls", CatTarget, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, periodsNone, marketsIndividual,
		[]string{"World Bowls Championship", "Commonwealth Games Bowls"}, 3},
	{"petanque", "Pétanque", CatTarget, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, periodsNone, marketsIndividual,
		[]string{"Pétanque World Championships"}, 3},

	// -----------------------------------------------------------------
	// Cue sports
	// -----------------------------------------------------------------
	{"snooker", "Snooker", CatCue, ScoringFrames, []Format{FormatMatch, FormatTournament}, false, periodsNone, marketsFrames,
		[]string{"World Snooker Championship", "UK Championship", "The Masters"}, 0},
	{"pool", "Pool", CatCue, ScoringFrames, []Format{FormatMatch, FormatTournament}, false, periodsNone, marketsFrames,
		[]string{"World Pool Championship", "Mosconi Cup"}, 0},
	{"billiards", "English Billiards", CatCue, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, periodsNone, marketsFrames,
		[]string{"World Billiards Championship"}, 0},
	{"carom", "Carom Billiards", CatCue, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, periodsNone, marketsFrames,
		[]string{"Three-Cushion World Championship"}, 0},

	// -----------------------------------------------------------------
	// Equestrian
	// -----------------------------------------------------------------
	{"show-jumping", "Show Jumping", CatEquestrian, ScoringPoints, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"FEI Jumping World Cup", "Olympic Show Jumping"}, 3},
	{"dressage", "Dressage", CatEquestrian, ScoringJudged, []Format{FormatTournament}, false, periodsNone, marketsField,
		[]string{"FEI Dressage World Cup", "Olympic Dressage"}, 3},
	{"eventing", "Eventing", CatEquestrian, ScoringPoints, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsField,
		[]string{"Badminton Horse Trials", "Burghley Horse Trials"}, 3},
	{"polo", "Polo", CatEquestrian, ScoringGoals, []Format{FormatMatch, FormatTournament}, false, []string{"Chukka 1", "Chukka 2", "Chukka 3", "Chukka 4"}, marketsTeamNoDraw,
		[]string{"Argentine Open", "British Open Polo Championship"}, 0},
	{"rodeo", "Rodeo", CatEquestrian, ScoringJudged, []Format{FormatTournament}, false, periodsNone, marketsField,
		[]string{"National Finals Rodeo", "PBR World Finals"}, 3},

	// -----------------------------------------------------------------
	// Action sports
	// -----------------------------------------------------------------
	{"skateboarding", "Skateboarding", CatExtreme, ScoringJudged, []Format{FormatTournament}, false, periodsNone, marketsField,
		[]string{"Street League Skateboarding", "X Games", "Olympic Skateboarding"}, 3},
	{"sport-climbing", "Sport Climbing", CatExtreme, ScoringPoints, []Format{FormatTournament}, false, periodsNone, marketsField,
		[]string{"IFSC Climbing World Cup", "Olympic Sport Climbing"}, 3},
	{"cliff-diving", "Cliff Diving", CatExtreme, ScoringJudged, []Format{FormatTournament}, false, periodsNone, marketsField,
		[]string{"Red Bull Cliff Diving World Series"}, 3},
	{"freestyle-motocross", "Freestyle Motocross", CatExtreme, ScoringJudged, []Format{FormatTournament}, false, periodsNone, marketsField,
		[]string{"X Games", "Nitro World Games"}, 3},

	// -----------------------------------------------------------------
	// Mind sports
	// -----------------------------------------------------------------
	{"chess", "Chess", CatMind, ScoringPoints, []Format{FormatMatch, FormatTournament}, true, periodsNone, marketsIndividual,
		[]string{"World Chess Championship", "Candidates Tournament", "Chess World Cup"}, 3},
	{"poker", "Poker", CatMind, ScoringPoints, []Format{FormatTournament}, false, periodsNone, marketsField,
		[]string{"World Series of Poker", "European Poker Tour"}, 3},
	{"backgammon", "Backgammon", CatMind, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, periodsNone, marketsIndividual,
		[]string{"World Backgammon Championship"}, 3},
	{"bridge", "Contract Bridge", CatMind, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, periodsNone, marketsIndividual,
		[]string{"Bermuda Bowl", "World Bridge Championships"}, 3},
	{"go", "Go", CatMind, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, periodsNone, marketsIndividual,
		[]string{"Ing Cup", "LG Cup"}, 3},
	{"draughts", "Draughts", CatMind, ScoringPoints, []Format{FormatMatch, FormatTournament}, true, periodsNone, marketsIndividual,
		[]string{"World Draughts Championship"}, 3},
	{"scrabble", "Scrabble", CatMind, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, periodsNone, marketsIndividual,
		[]string{"World Scrabble Championship"}, 3},

	// -----------------------------------------------------------------
	// Esports
	// -----------------------------------------------------------------
	{"cs2", "Counter-Strike", CatEsports, ScoringMaps, []Format{FormatMatch, FormatTournament}, false, periodsMaps, marketsEsports,
		[]string{"BLAST Premier", "ESL Pro League", "IEM Katowice", "Majors"}, 0},
	{"dota-2", "Dota 2", CatEsports, ScoringMaps, []Format{FormatMatch, FormatTournament}, false, periodsMaps, marketsEsports,
		[]string{"The International", "ESL One", "DreamLeague"}, 0},
	{"league-of-legends", "League of Legends", CatEsports, ScoringMaps, []Format{FormatMatch, FormatTournament}, false, periodsMaps, marketsEsports,
		[]string{"LoL World Championship", "LEC", "LCK", "MSI"}, 0},
	{"valorant", "Valorant", CatEsports, ScoringMaps, []Format{FormatMatch, FormatTournament}, false, periodsMaps, marketsEsports,
		[]string{"VCT Champions", "VCT Masters"}, 0},
	{"overwatch", "Overwatch", CatEsports, ScoringMaps, []Format{FormatMatch, FormatTournament}, false, periodsMaps, marketsEsports,
		[]string{"Overwatch Champions Series"}, 0},
	{"rocket-league", "Rocket League", CatEsports, ScoringMaps, []Format{FormatMatch, FormatTournament}, false, periodsMaps, marketsEsports,
		[]string{"RLCS", "RLCS World Championship"}, 0},
	{"call-of-duty", "Call of Duty", CatEsports, ScoringMaps, []Format{FormatMatch, FormatTournament}, false, periodsMaps, marketsEsports,
		[]string{"Call of Duty League", "CDL Championship"}, 0},
	{"rainbow-six", "Rainbow Six Siege", CatEsports, ScoringMaps, []Format{FormatMatch, FormatTournament}, false, periodsMaps, marketsEsports,
		[]string{"Six Invitational", "R6 Major"}, 0},
	{"starcraft-2", "StarCraft II", CatEsports, ScoringMaps, []Format{FormatMatch, FormatTournament}, false, periodsMaps, marketsEsports,
		[]string{"ESL Pro Tour", "GSL"}, 0},
	{"apex-legends", "Apex Legends", CatEsports, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, periodsMaps, marketsEsports,
		[]string{"ALGS Championship"}, 0},
	{"pubg", "PUBG", CatEsports, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, periodsMaps, marketsEsports,
		[]string{"PUBG Global Championship"}, 0},
	{"fortnite", "Fortnite", CatEsports, ScoringPoints, []Format{FormatTournament}, false, periodsNone, marketsField,
		[]string{"Fortnite Champion Series", "FNCS Global Championship"}, 3},
	{"mobile-legends", "Mobile Legends", CatEsports, ScoringMaps, []Format{FormatMatch, FormatTournament}, false, periodsMaps, marketsEsports,
		[]string{"M-Series World Championship", "MPL"}, 0},
	{"honor-of-kings", "Honor of Kings", CatEsports, ScoringMaps, []Format{FormatMatch, FormatTournament}, false, periodsMaps, marketsEsports,
		[]string{"King Pro League", "Honor of Kings World Champion Cup"}, 0},
	{"ea-fc-esports", "EA FC Esports", CatEsports, ScoringGoals, []Format{FormatMatch, FormatTournament}, true, periodsHalves, marketsEsports,
		[]string{"FC Pro World Championship", "eChampions League"}, 0},
	{"nba-2k-esports", "NBA 2K League", CatEsports, ScoringPoints, []Format{FormatMatch, FormatTournament}, false, periodsQuarters, marketsEsports,
		[]string{"NBA 2K League"}, 0},
	{"fighting-games", "Fighting Games", CatEsports, ScoringMaps, []Format{FormatMatch, FormatTournament}, false, periodsMaps, marketsEsports,
		[]string{"EVO", "Street Fighter League", "Tekken World Tour"}, 0},
	{"sim-racing", "Sim Racing", CatEsports, ScoringPosition, []Format{FormatRace, FormatTournament}, false, periodsNone, marketsMotorsport,
		[]string{"F1 Esports Series", "Gran Turismo World Series"}, 3},
	{"hearthstone", "Hearthstone", CatEsports, ScoringMaps, []Format{FormatMatch, FormatTournament}, false, periodsMaps, marketsEsports,
		[]string{"Hearthstone World Championship"}, 0},

	// -----------------------------------------------------------------
	// Multi-sport events
	// -----------------------------------------------------------------
	{"summer-olympics", "Summer Olympics", CatMultiSport, ScoringMedals, []Format{FormatTournament}, false, periodsNone, marketsMedals,
		[]string{"Olympic Games"}, 3},
	{"winter-olympics", "Winter Olympics", CatMultiSport, ScoringMedals, []Format{FormatTournament}, false, periodsNone, marketsMedals,
		[]string{"Olympic Winter Games"}, 3},
	{"paralympics", "Paralympics", CatMultiSport, ScoringMedals, []Format{FormatTournament}, false, periodsNone, marketsMedals,
		[]string{"Paralympic Games"}, 3},
	{"commonwealth-games", "Commonwealth Games", CatMultiSport, ScoringMedals, []Format{FormatTournament}, false, periodsNone, marketsMedals,
		[]string{"Commonwealth Games"}, 3},
	{"asian-games", "Asian Games", CatMultiSport, ScoringMedals, []Format{FormatTournament}, false, periodsNone, marketsMedals,
		[]string{"Asian Games"}, 3},
	{"world-games", "World Games", CatMultiSport, ScoringMedals, []Format{FormatTournament}, false, periodsNone, marketsMedals,
		[]string{"The World Games"}, 3},
	{"university-games", "World University Games", CatMultiSport, ScoringMedals, []Format{FormatTournament}, false, periodsNone, marketsMedals,
		[]string{"FISU World University Games"}, 3},
}
